name: Kubernetes Deployment CI

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build And Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t venky2705/lead-management-k8s:latest \
            .

      - name: Deploy To EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            docker pull venky2705/lead-management-k8s:latest

            docker stop lead-management || true

            docker rm lead-management || true

            docker run -d \
              --name lead-management \
              -p 8000:8000 \
              venky2705/lead-management-k8s:latest